/**
 * DeployCenter — Data Import Script
 * Imports Users, Teams, TeamMembers, RolePermissions, and SystemParams
 * from a JSON file generated by export-data.ts.
 *
 * Usage (on new server, after prisma migrate deploy):
 *   npx ts-node scripts/import-data.ts [input-file]
 *   npx ts-node scripts/import-data.ts ./deploycenter-data-export.json
 *
 * Or during Docker boot via SEED_DATA_FILE env var (handled by docker-entrypoint.sh).
 *
 * Safe to re-run — uses upsert everywhere. Existing data is updated, nothing is deleted.
 */

import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';

dotenv.config({ path: path.resolve(process.cwd(), `.env.${process.env.NODE_ENV || 'prod'}`), override: true });

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({ datasources: { db: { url: process.env.DATABASE_URL } } });

async function main() {
  const inputFile = process.argv[2] ?? process.env.SEED_DATA_FILE ?? './deploycenter-data-export.json';
  const resolvedPath = path.resolve(inputFile);

  console.log('DeployCenter Data Import');
  console.log(`  DB   : ${(process.env.DATABASE_URL ?? '').replace(/:\/\/.*@/, '://***@')}`);
  console.log(`  File : ${resolvedPath}`);
  console.log('');

  if (!fs.existsSync(resolvedPath)) {
    console.error(`Import file not found: ${resolvedPath}`);
    process.exit(1);
  }

  let data: any;
  try {
    data = JSON.parse(fs.readFileSync(resolvedPath, 'utf8'));
  } catch (err: any) {
    console.error(`Failed to parse import file: ${err.message}`);
    process.exit(1);
  }

  const { users = [], teams = [], teamMembers = [], rolePermissions = [], systemParams = [], versionTemplates = [], skills = [], testerProfiles = [], testerSkills = [] } = data;

  let imported = { users: 0, teams: 0, teamMembers: 0, rolePermissions: 0, systemParams: 0, versionTemplates: 0, skills: 0, testerProfiles: 0, testerSkills: 0 };
  // Maps export userId → resolved userId in target DB (handles ID collisions via email match)
  const userIdMap = new Map<string, string>();

  try {
    // ── 1. Teams (no foreign key deps) ─────────────────────────────────────
    for (const team of teams) {
      await prisma.team.upsert({
        where: { id: team.id },
        update: {
          name:         team.name,
          description:  team.description ?? null,
          apps:         team.apps ?? [],
          active:       team.active ?? true,
          requiresPlan: team.requiresPlan ?? true,
        },
        create: {
          id:           team.id,
          name:         team.name,
          description:  team.description ?? null,
          apps:         team.apps ?? [],
          active:       team.active ?? true,
          requiresPlan: team.requiresPlan ?? true,
          createdAt:    team.createdAt ? new Date(team.createdAt) : new Date(),
        },
      });
      imported.teams++;
    }

    // ── 2. Users — upsert by email (true unique key) ──────────────────────
    // Upsert by email handles re-runs safely and resolves ID mismatches
    // (e.g. target DB already had a user created with a different UUID).
    // Passwords are hashed — they transfer verbatim and work immediately.
    for (const user of users) {
      const existing = await prisma.user.findUnique({ where: { email: user.email } });
      if (existing) {
        // User exists (possibly with a different ID) — update fields, keep existing ID
        await prisma.user.update({
          where: { email: user.email },
          data: {
            fullName: user.fullName,
            phone:    user.phone ?? null,
            password: user.password,
            role:     user.role,
            active:   user.active ?? true,
          },
        });
        userIdMap.set(user.id, existing.id);
      } else {
        await prisma.user.create({
          data: {
            id:        user.id,
            fullName:  user.fullName,
            email:     user.email,
            phone:     user.phone ?? null,
            password:  user.password,
            role:      user.role,
            active:    user.active ?? true,
            createdAt: user.createdAt ? new Date(user.createdAt) : new Date(),
            updatedAt: user.updatedAt ? new Date(user.updatedAt) : new Date(),
          },
        });
        userIdMap.set(user.id, user.id);
      }
      imported.users++;
    }

    // ── 3. TeamMembers (use resolved IDs from userIdMap) ──────────────────
    for (const tm of teamMembers) {
      const resolvedUserId = userIdMap.get(tm.userId) ?? tm.userId;
      // Verify the user actually exists before linking (skip orphaned members)
      const userExists = await prisma.user.findUnique({ where: { id: resolvedUserId } });
      if (!userExists) continue;
      await prisma.teamMember.upsert({
        where: { userId_teamId: { userId: resolvedUserId, teamId: tm.teamId } },
        update: { isLead: tm.isLead ?? false },
        create: { userId: resolvedUserId, teamId: tm.teamId, isLead: tm.isLead ?? false },
      });
      imported.teamMembers++;
    }

    // ── 4. RolePermissions ────────────────────────────────────────────────────
    for (const rp of rolePermissions) {
      await prisma.rolePermissions.upsert({
        where: { role: rp.role },
        update: { permissions: rp.permissions },
        create: { role: rp.role, permissions: rp.permissions },
      });
      imported.rolePermissions++;
    }

    // ── 5. SystemParams — only update if destination value is empty ────────────
    // This prevents overwriting values the admin already configured on the new server.
    for (const sp of systemParams) {
      const existing = await prisma.systemParam.findUnique({ where: { key: sp.key } });
      if (!existing) {
        await prisma.systemParam.create({
          data: { key: sp.key, value: sp.value, label: sp.label ?? sp.key, type: sp.type ?? 'text' },
        });
        imported.systemParams++;
      } else if (!existing.value?.trim()) {
        // Only fill in if currently empty — never overwrite a configured value
        await prisma.systemParam.update({
          where: { key: sp.key },
          data:  { value: sp.value },
        });
        imported.systemParams++;
      }
    }

    // ── 6. VersionTemplates — upsert by id ───────────────────────────────────
    for (const vt of versionTemplates) {
      const resolvedCreatedBy = userIdMap.get(vt.createdBy) ?? vt.createdBy;
      const creatorExists = await prisma.user.findUnique({ where: { id: resolvedCreatedBy } });
      if (!creatorExists) continue;
      await prisma.versionTemplate.upsert({
        where: { id: vt.id },
        update: { name: vt.name, description: vt.description ?? null, structure: vt.structure },
        create: {
          id:          vt.id,
          name:        vt.name,
          description: vt.description ?? null,
          structure:   vt.structure,
          createdBy:   resolvedCreatedBy,
          createdAt:   vt.createdAt ? new Date(vt.createdAt) : new Date(),
          updatedAt:   vt.updatedAt ? new Date(vt.updatedAt) : new Date(),
        },
      });
      imported.versionTemplates++;
    }

    // ── 7. Skills — upsert by name (the actual unique key; ids are random per-install) ──
    const skillIdMap = new Map<string, string>();
    for (const sk of skills) {
      const saved = await prisma.skill.upsert({
        where: { name: sk.name },
        update: { type: sk.type, weight: sk.weight ?? 3 },
        create: { id: sk.id, name: sk.name, type: sk.type, weight: sk.weight ?? 3, createdAt: sk.createdAt ? new Date(sk.createdAt) : new Date() },
      });
      skillIdMap.set(sk.id, saved.id);
      imported.skills++;
    }

    // ── 8. TesterProfiles (resolved userId; skip if the user doesn't exist) ──
    for (const tp of testerProfiles) {
      const resolvedUserId = userIdMap.get(tp.userId) ?? tp.userId;
      const userExists = await prisma.user.findUnique({ where: { id: resolvedUserId } });
      if (!userExists) continue;
      await prisma.testerProfile.upsert({
        where: { userId: resolvedUserId },
        update: { isActive: tp.isActive ?? true },
        create: { userId: resolvedUserId, isActive: tp.isActive ?? true, createdAt: tp.createdAt ? new Date(tp.createdAt) : new Date() },
      });
      imported.testerProfiles++;
    }

    // ── 9. TesterSkills — the skill matrix itself (resolved userId + skillId) ──
    for (const ts of testerSkills) {
      const resolvedUserId = userIdMap.get(ts.userId) ?? ts.userId;
      const resolvedSkillId = skillIdMap.get(ts.skillId) ?? ts.skillId;
      const [testerExists, skillExists] = await Promise.all([
        prisma.testerProfile.findUnique({ where: { userId: resolvedUserId } }),
        prisma.skill.findUnique({ where: { id: resolvedSkillId } }),
      ]);
      if (!testerExists || !skillExists) continue;
      await prisma.testerSkill.upsert({
        where: { userId_skillId: { userId: resolvedUserId, skillId: resolvedSkillId } },
        update: { level: ts.level ?? 1 },
        create: { userId: resolvedUserId, skillId: resolvedSkillId, level: ts.level ?? 1 },
      });
      imported.testerSkills++;
    }

    console.log('✅ Import complete:');
    console.log(`   Users          : ${imported.users}`);
    console.log(`   Teams          : ${imported.teams}`);
    console.log(`   Team Members   : ${imported.teamMembers}`);
    console.log(`   Role Perms     : ${imported.rolePermissions}`);
    console.log(`   System Params  : ${imported.systemParams}`);
    console.log(`   Templates      : ${imported.versionTemplates}`);
    console.log(`   Skills         : ${imported.skills}`);
    console.log(`   Tester Profiles: ${imported.testerProfiles}`);
    console.log(`   Tester Skills  : ${imported.testerSkills}`);
    console.log('');
  } catch (err: any) {
    console.error(`Import failed: ${err.message}`);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
