// Field pools for the open-production-defects screen's admin-configurable
// table columns and detail-screen fields. Two separate pools because they
// come from two different backend queries with different field breadth —
// see OpenProdDefectsView.tsx and qc.service.ts's DEFECT_BY_ID_SQL.

export interface FieldDef { key: string; label: string; }

// Matches OpenProdDefectMonthDto (backend qc.service.ts) — the ~15 fields
// already returned by the monthly-history query. monthDate/monthLabel are
// the grouping key (the screen's own month selector), not row fields, so
// they're excluded from the choosable pool.
export const TABLE_COLUMN_FIELDS: FieldDef[] = [
  { key: 'defectId',      label: 'Defect ID' },
  { key: 'title',         label: 'Title' },
  { key: 'severity',      label: 'Severity' },
  { key: 'priority',      label: 'Priority' },
  { key: 'responsibility',label: 'Responsibility' },
  { key: 'assignedTo',    label: 'Assigned To' },
  { key: 'qaTester',      label: 'QA' },
  { key: 'area',          label: 'CR' },
  { key: 'crReferenceNumber', label: 'CR Reference Number' },
  { key: 'bugType',       label: 'Bug Type' },
  { key: 'fixType',       label: 'Fix Type' },
  { key: 'statusAtMonth', label: 'Status (Selected Month)' },
  { key: 'currentStatus', label: 'Current Status' },
  { key: 'testPhase',     label: 'Test Phase' },
  { key: 'detectedBy',    label: 'Detected By' },
  { key: 'detectedDate',  label: 'Detected on Date' },
  { key: 'closedBy',      label: 'Closed By' },
  { key: 'reopenYn',      label: 'Reopen Y/N' },
  { key: 'releaseId',     label: 'Release ID' },
  { key: 'environment',   label: 'Environment' },
  { key: 'subModule',     label: 'Sub Module' },
  { key: 'mainModule',    label: 'Main Module' },
  { key: 'platform',      label: 'Platform' },
  { key: 'estimatedFixTime', label: 'Estimated Fix Time' },
  { key: 'actualFixTime',   label: 'Fix Time' },
  { key: 'deploymentReason', label: 'Deployment Reason' },
];

// Matches TargetDefectDto (backend qc.service.ts) — the full real BUG-table
// field set, same shape already used by the TARGET-CR and Incidents/RCA
// screens (mapRowToTargetDefect).
export const DETAIL_FIELDS: FieldDef[] = [
  { key: 'id',                      label: 'Defect ID' },
  { key: 'title',                   label: 'Title' },
  { key: 'subject',                 label: 'Subject' },
  { key: 'summary',                 label: 'Summary' },
  { key: 'description',             label: 'Description' },
  { key: 'notes',                   label: 'Comments' },
  { key: 'status',                  label: 'Bug Status' },
  { key: 'severity',                label: 'Severity' },
  { key: 'priority',                label: 'Priority' },
  { key: 'secondaryPriority',       label: 'Secondary Priority' },
  { key: 'reproducible',            label: 'Reproducible Y/N' },
  { key: 'assignedTo',              label: 'Assigned To' },
  { key: 'qaTester',                label: 'QA' },
  { key: 'detectedBy',              label: 'Detected By' },
  { key: 'detectedOnDate',          label: 'Detected on Date' },
  { key: 'closedBy',                label: 'Closed By' },
  { key: 'system',                  label: 'Project' },
  { key: 'environment',             label: 'Environment' },
  { key: 'environmentComponent',    label: 'Environment Component' },
  { key: 'responsibility',          label: 'Responsibility' },
  { key: 'defectResponsible',       label: 'Defect Responsible' },
  { key: 'escDefectResponsible',    label: 'Esc Defect Responsible' },
  { key: 'testPhase',               label: 'Test Phase' },
  { key: 'defectType',              label: 'Bug Type' },
  { key: 'fixType',                 label: 'Fix Type' },
  { key: 'estimatedFixTime',        label: 'Estimated Fix Time' },
  { key: 'actualFixTime',           label: 'Fix Time' },
  { key: 'estimateFixTime',         label: 'Estimate Fix Time' },
  { key: 'fixedUntil',              label: 'Fixed Until' },
  { key: 'fixedInProd',             label: 'Fixed in Prod' },
  { key: 'deploymentReason',        label: 'Deployment Reason' },
  { key: 'deploymentCategory',      label: 'Deployment Category' },
  { key: 'deploymentDateProd',      label: 'Deployment Date (Prod)' },
  { key: 'crHbrNumberReference',    label: 'CR/HBR Number reference' },
  { key: 'crReferenceNumber',       label: 'CR Reference Number' },
  { key: 'crStatus',                label: 'CR Status' },
  { key: 'vendorStatus',            label: 'Vendor Status' },
  { key: 'vendorAssignTo',          label: 'Assign To (Vendor)' },
  { key: 'responseDate',            label: 'Response Date' },
  { key: 'supportReferenceNumber',  label: 'Support Reference Number' },
  { key: 'supportStatus',           label: 'Support Status' },
  { key: 'subModule',               label: 'Sub Module' },
  { key: 'mainModule',              label: 'Main Module' },
  { key: 'systemComponent',         label: 'System Component' },
  { key: 'reason',                  label: 'Reason' },
  { key: 'category',                label: 'Category' },
  { key: 'itemType',                label: 'Item Type' },
  { key: 'platform',                label: 'Platform' },
  { key: 'modified',                label: 'Modified' },
  { key: 'detectedInRelease',       label: 'Detected in Release' },
  { key: 'detectedInCycle',         label: 'Detected in Cycle' },
  { key: 'targetRelease',           label: 'Target Release' },
  { key: 'targetCycle',             label: 'Target Cycle' },
  { key: 'targetType',              label: 'Target Type' },
  { key: 'targetReleaseReason',     label: 'Target Release Reason' },
  { key: 'targetScopeApproved',     label: 'Target Scope Approved' },
  { key: 'dropNumber',              label: 'Drop#' },
  { key: 'reopenYn',                label: 'Reopen Y/N' },
  { key: 'influence',               label: 'Influence' },
  { key: 'impact',                  label: 'Impact' },
  { key: 'releaseDefect',           label: 'Release Defect' },
  { key: 'businessProcess',         label: 'Business Process' },
  { key: 'mainBusinessProcess',     label: 'Main Business Process' },
  { key: 'foundByAutomation',       label: 'Found By Automation' },
  { key: 'forRegressionTest',       label: 'For Regression Test' },
  { key: 'productionReason',        label: 'Production Reason' },
  { key: 'willBeTestAtGoLive',      label: 'Will Be Test At Go Live' },
  { key: 'toBeTestedOnProd',        label: 'To Be Tested On Prod' },
];

export const TABLE_FIELD_LABEL: Record<string, string> = Object.fromEntries(TABLE_COLUMN_FIELDS.map(f => [f.key, f.label]));
export const DETAIL_FIELD_LABEL: Record<string, string> = Object.fromEntries(DETAIL_FIELDS.map(f => [f.key, f.label]));
